### ISSUE TITLE
Cant connect with Android phones

### ISSUE THREAD

**Issue by LucasCoraca** [anthony96922/mt7601u-ap#1]
I compiled the driver on Linux raspberrypi 3.18.11+ #781 PREEMPT Tue Apr 21 18:02:18 BST 2015 armv6l GNU/Linux, no problem there, it run and create a access point no problem, i can connect and ssh with windows mac and ios via the access point, but when i try to connect with android i have no success, it keep in a loop of obtaining IP address. 

Any ideas? i really need this to work for a project of mine.

**Comment by anthony96922** [comment]
Did you set up a dhcp server?

**Comment by LucasCoraca** [comment]
i found the problem, i had to manually set the ip on the android phone, everything works fine thanks
