### ISSUE TITLE
modprobe: FATAL: Module mt7601Uap not found in directory /lib/modules/5.2.0-2parrot1-amd64

### ISSUE THREAD

**Issue by arghyadipchak** [Anthony96922/mt7601u-ap#14]
All commands worked perfectly.
make made no problems, it was made,
But i couldn't load the module.

modprobe: FATAL: Module mt7601Uap not found in directory /lib/modules/5.2.0-2parrot1-amd64

This was the error in Parrot OS System.

**Comment by Anthony96922** [comment]
What's the output of "modinfo mt7601Uap" ?

**Comment by arghyadipchak** [comment]
modinfo: ERROR: Module mt7601Uap not found.

**Comment by arghyadipchak** [comment]
Hey, The above problem got solved. I reinstalled it, and it worked.
But still the wlan1 is not supporting ap mode..
How do i select the ap drivers for my wlan1??

**Comment by Anthony96922** [comment]
Is your wlan1 mt7601u?

**Comment by arghyadipchak** [comment]
Yes

**Comment by Anthony96922** [comment]
What is the output of lsmod?

**Comment by arghyadipchak** [comment]
rfcomm                 86016  16
bbswitch               20480  0
ctr                    16384  2
ccm                    20480  6
cmac                   16384  1
xfrm_user              40960  2
xfrm_algo              16384  1 xfrm_user
bnep                   28672  2
nvidia              19111936  15
ipmi_devintf           20480  0
ipmi_msghandler        65536  2 ipmi_devintf,nvidia
binfmt_misc            24576  1
mt7601Uap             724992  0
wl                   6467584  0
iwlmvm                323584  0
btusb                  57344  0
arc4                   16384  4
btrtl                  20480  1 btusb
uvcvideo              114688  0
videobuf2_vmalloc      20480  1 uvcvideo
btbcm                  16384  1 btusb
iwlwifi               274432  1 iwlmvm
videobuf2_memops       20480  1 videobuf2_vmalloc
videobuf2_v4l2         28672  1 uvcvideo
mt7601u               131072  0
videobuf2_common       57344  2 videobuf2_v4l2,uvcvideo
intel_rapl             28672  0
btintel                28672  1 btusb
snd_soc_skl           118784  0
x86_pkg_temp_thermal    20480  0
intel_powerclamp       20480  0
coretemp               20480  0
videodev              233472  3 videobuf2_v4l2,uvcvideo,videobuf2_common
snd_soc_skl_ipc        69632  1 snd_soc_skl
snd_soc_sst_ipc        20480  1 snd_soc_skl_ipc
media                  57344  4 videodev,videobuf2_v4l2,uvcvideo,videobuf2_common
snd_soc_sst_dsp        40960  1 snd_soc_skl_ipc
snd_hda_ext_core       36864  1 snd_soc_skl
snd_soc_acpi_intel_match    28672  1 snd_soc_skl
kvm_intel             270336  0
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,snd_soc_skl
snd_hda_codec_hdmi     69632  1
snd_soc_core          270336  1 snd_soc_skl
snd_compress           28672  1 snd_soc_core
snd_hda_codec_generic    90112  1
ledtrig_audio          16384  1 snd_hda_codec_generic
kvm                   749568  1 kvm_intel
mac80211              868352  2 iwlmvm,mt7601u
button                 20480  0
snd_hda_intel          49152  4
snd_hda_codec         159744  3 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel
bluetooth             655360  41 btrtl,btintel,btbcm,bnep,btusb,rfcomm
snd_hda_core          102400  6 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_soc_skl
irqbypass              16384  1 kvm
drbg                   28672  1
snd_hwdep              16384  1 snd_hda_codec
ansi_cprng             16384  0
iTCO_wdt               16384  0
ideapad_laptop         24576  0
snd_pcm               118784  7 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_soc_core,snd_soc_skl,snd_hda_core
snd_timer              40960  1 snd_pcm
tpm_crb                20480  0
tpm_tis                16384  0
intel_cstate           16384  0
ecdh_generic           16384  2 bluetooth
intel_uncore          139264  0
ecc                    32768  1 ecdh_generic
battery                20480  0
acpi_pad               28672  0
intel_rapl_perf        16384  0
ac                     16384  0
idma64                 20480  0
sparse_keymap          16384  1 ideapad_laptop
iTCO_vendor_support    16384  1 iTCO_wdt
watchdog               28672  1 iTCO_wdt
snd                    98304  17 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_timer,snd_compress,snd_soc_core,snd_pcm
joydev                 28672  0
cfg80211              819200  5 wl,iwlmvm,mt7601u,iwlwifi,mac80211
evdev                  28672  18
tpm_tis_core           24576  1 tpm_tis
mei_me                 45056  0
mei                   122880  1 mei_me
sg                     40960  0
pcc_cpufreq            20480  0
elan_i2c               49152  0
tpm                    73728  3 tpm_tis,tpm_crb,tpm_tis_core
intel_pch_thermal      16384  0
rfkill                 28672  8 bluetooth,ideapad_laptop,cfg80211
pcspkr                 16384  0
soundcore              16384  1 snd
serio_raw              20480  0
wmi_bmof               16384  0
rng_core               16384  2 tpm
squashfs               65536  10
loop                   36864  20
parport_pc             32768  0
ppdev                  24576  0
lp                     20480  0
parport                61440  3 parport_pc,lp,ppdev
ip_tables              32768  0
x_tables               49152  1 ip_tables
autofs4                53248  2
raid10                 65536  0
raid456               176128  0
async_raid6_recov      24576  1 raid456
async_memcpy           20480  2 raid456,async_raid6_recov
async_pq               20480  2 raid456,async_raid6_recov
async_xor              20480  3 async_pq,raid456,async_raid6_recov
async_tx               20480  5 async_pq,async_memcpy,async_xor,raid456,async_raid6_recov
raid1                  49152  0
raid0                  24576  0
multipath              20480  0
linear                 20480  0
md_mod                172032  6 raid1,raid10,raid0,linear,raid456,multipath
btrfs                1470464  1
xor                    24576  2 async_xor,btrfs
zstd_decompress        86016  2 squashfs,btrfs
zstd_compress         172032  1 btrfs
raid6_pq              122880  4 async_pq,btrfs,raid456,async_raid6_recov
libcrc32c              16384  2 btrfs,raid456
ext4                  753664  1
crc16                  16384  2 bluetooth,ext4
mbcache                16384  1 ext4
jbd2                  126976  1 ext4
crc32c_generic         16384  0
nls_ascii              16384  0
hid_generic            16384  0
usbhid                 65536  0
sd_mod                 57344  4
crct10dif_pclmul       16384  1
crc32_pclmul           16384  0
crc32c_intel           24576  3
ghash_clmulni_intel    16384  0
i915                 1871872  3
i2c_algo_bit           16384  1 i915
i2c_designware_platform    16384  0
i2c_designware_core    24576  1 i2c_designware_platform
drm_kms_helper        225280  1 i915
aesni_intel           372736  6
aes_x86_64             20480  1 aesni_intel
crypto_simd            16384  1 aesni_intel
r8169                  98304  0
xhci_pci               20480  0
ahci                   40960  3
realtek                20480  1
libahci                40960  1 ahci
xhci_hcd              278528  1 xhci_pci
cryptd                 24576  2 crypto_simd,ghash_clmulni_intel
glue_helper            16384  1 aesni_intel
libata                278528  2 libahci,ahci
i2c_i801               32768  0
intel_lpss_pci         20480  0
libphy                 94208  2 r8169,realtek
usbcore               299008  7 mt7601Uap,xhci_hcd,usbhid,mt7601u,uvcvideo,btusb,xhci_pci
drm                   532480  4 drm_kms_helper,i915
scsi_mod              245760  3 sd_mod,libata,sg
intel_lpss             16384  1 intel_lpss_pci
i2c_hid                32768  0
mfd_core               16384  1 intel_lpss
usb_common             16384  1 usbcore
hid                   139264  3 i2c_hid,usbhid,hid_generic
wmi                    32768  2 wmi_bmof,ideapad_laptop
video                  49152  2 ideapad_laptop,i915

**Comment by Anthony96922** [comment]
The stock mt7601u driver is loaded. You'll need to unload it by running `sudo modprobe -r mt7601u`.

**Comment by arghyadipchak** [comment]
I did it. But now I am facing the following problems:
First of all I did "modprobe -r mt7601u" and then i plugged out my adapter and re-inserted it.
But then i became ra0. And so I can no more use it for the things I needed like airmon-ng and WiFi-Pumpkin.

And then I rebooted my system it was again wlan1 with mt7601u.

**Comment by arghyadipchak** [comment]
Is there any way that it would remain the same but support ap mode??

**Comment by Anthony96922** [comment]
So you're using the default driver. You'll need to blacklist the stock driver so the new one can be used. Create /etc/modprobe.d/mt7601u.conf with the following contents:
```
blacklist mt7601u
```
Unfortunately you can't use it for airmon-ng with this driver.

**Comment by arghyadipchak** [comment]
Ok Thanks.
