### ISSUE TITLE
ra0 no wireless extensions

### ISSUE THREAD

**Issue by building-software-2018** [Anthony96922/mt7601u-ap#15]
I install driver successfully, wifi network "test" is on. But i run command iwconfig, it displays:

    ra0       no wireless extensions.

So that, I can't use [https://github.com/FluxionNetwork/fluxion](fluxion) with it. 

ifconfig info

    ra0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether f4:28:53:1b:d9:4c  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lsusb info

    Bus 003 Device 006: ID 148f:7601 Ralink Technology, Corp. MT7601U Wireless Adapter

I run on Ubuntu 18.04.3 LTS

**Comment by Anthony96922** [comment]
From what I've read on the fluxion wiki, it needs monitor mode support and this driver doesn't have it. Closing.

**Comment by kuhiu** [comment]
HI! I ve the same problem

I install driver successfully, wifi network "test" is on. But i run command iwconfig, it displays:

ra0       no wireless extensions

Im not trying to use fluxion. I cant connect to "test" from my phone.
