### ISSUE TITLE
nothing has changed

### ISSUE THREAD

**Issue by arx81** [Anthony96922/mt7601u-ap#7]
I installed the driver as a guide even correcting the error

EXTRA_CFLAGS + = - WNO-implicit-function-declaration
EXTRA_CFLAGS + = - WNO-incompatible-pointer-types

in config.mk

but at the end of the make install nothing changes me, the driver is always the same as before.

`wlx00e1b0117ad1  IEEE 802.11  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off `

he always tells me: 

`  Supported interface modes:
                 * managed
                 * monitor
`

**Comment by arx81** [comment]
use armbian ubuntu bionic Linux orangepione 4.14.70-sunxi

**Comment by Anthony96922** [comment]
Make sure you blacklist the default mt7601u driver.
